/* ── 点击面板内部不能把面板关掉（这是一个真实回归） ── */

console.log('== 点面板内部：必须留下 ==')
let tree = await openPanel()
console.log('  开面板后:', (await chipTree()).props.className, ' 监听器:', (fakeDoc._listeners['pointerdown'] || []).length)
ok('面板已打开', (await chipTree()).props.className.indexOf('dsh-git-chip-open') >= 0)
fakeDoc.fire('pointerdown', { target: INSIDE })
await wait(15)
console.log('  点内部后:', (await chipTree()).props.className, ' 监听器:', (fakeDoc._listeners['pointerdown'] || []).length)
tree = await settle('pop')
console.log('  settle 之后:', (await chipTree()).props.className, ' 监听器:', (fakeDoc._listeners['pointerdown'] || []).length)
ok('点内部后仍然打开', (await chipTree()).props.className.indexOf('dsh-git-chip-open') >= 0)
ok('面板内容还在（标签页在）', textOf(tree).indexOf('历史') >= 0)

console.log('')
console.log('== 连续点内部多次也不能关 ==')
console.log('  pointerdown 监听器数:', (fakeDoc._listeners['pointerdown'] || []).length)
console.log('  panelNode.contains(INSIDE):', panelNodeObj.contains(INSIDE), ' 是否同一个对象:', panelNodeObj === panelNodeObj)
for (let i = 0; i < 3; i += 1) {
  fakeDoc.fire('pointerdown', { target: INSIDE })
  await wait(10)
  console.log('  第 ' + (i + 1) + ' 次点击后 chip class:', (await chipTree()).props.className)
}
await settle('pop')
ok('点三次内部还是开着', (await chipTree()).props.className.indexOf('dsh-git-chip-open') >= 0)

console.log('')
console.log('== 点外面：应该关掉 ==')
fakeDoc.fire('pointerdown', { target: OUTSIDE })
await wait(15)
await settle('pop')
ok('点外面关掉了', (await chipTree()).props.className.indexOf('dsh-git-chip-open') < 0)

console.log('')
console.log('== Esc 也能关 ==')
await openPanel()
ok('重新打开', (await chipTree()).props.className.indexOf('dsh-git-chip-open') >= 0)
fakeDoc.fire('keydown', { key: 'Escape' })
await wait(15)
await settle('pop')
ok('Esc 关掉了', (await chipTree()).props.className.indexOf('dsh-git-chip-open') < 0)

console.log('')
console.log('== 切换器开着时，点面板内部也不该关面板 ==')
await openPanel()
tree = await settle('pop')
byClass(tree, 'dsh-git-branch-chip')[0].props.onClick()
await wait(10)
tree = await settle('pop')
ok('切换器开着', byClass(tree, 'dsh-git-switch').length === 1)
fakeDoc.fire('pointerdown', { target: INSIDE })
await wait(15)
tree = await settle('pop')
ok('面板还开着', (await chipTree()).props.className.indexOf('dsh-git-chip-open') >= 0)
ok('切换器收起了', byClass(tree, 'dsh-git-switch').length === 0)

console.log('')
console.log('== 点浮层卡片内部：谁都不该关 ==')
byClass(tree, 'dsh-git-branch-chip')[0].props.onClick()
await wait(10)
tree = await settle('pop')
ok('切换器又开了', byClass(tree, 'dsh-git-switch').length === 1)
fakeDoc.fire('pointerdown', { target: IN_CARD })
await wait(15)
tree = await settle('pop')
ok('卡片还在', byClass(tree, 'dsh-git-switch').length === 1)
ok('面板还在', (await chipTree()).props.className.indexOf('dsh-git-chip-open') >= 0)

console.log('')
console.log('== 点输入框旁边的按钮：不该关面板 ==')
fakeDoc.fire('pointerdown', { target: IN_CHIP })
await wait(15)
await settle('pop')
ok('面板还在（按钮自己决定开合）', (await chipTree()).props.className.indexOf('dsh-git-chip-open') >= 0)

console.log('')
console.log('== 选中分支不再冒出操作条 ==')
let t8 = await openPanel()
t8 = await settle('pop')
const localRow = collect(t8).find((n) => typeof n.props.className === 'string' && n.props.className.indexOf('dsh-git-trow') >= 0 && textOf(n) === 'feature')
if (localRow === undefined) {
  console.log('  分支树里没有名为 feature 的行，改用第一行分支行')
} else {
  localRow.props.onClick()
  await wait(15)
  t8 = await settle('pop')
}
ok('没有 side-actions 条了', byClass(t8, 'dsh-git-side-actions').length === 0)
ok('工具栏本身还在', byClass(t8, 'dsh-git-tools').length === 1)
console.log('  工具栏按钮:', JSON.stringify(buttons(byClass(t8, 'dsh-git-tools')[0]).map(textOf)))
ok('工具栏里不再混入分支名', buttons(byClass(t8, 'dsh-git-tools')[0]).every((b) => textOf(b) !== '切换' && textOf(b) !== '合并' && textOf(b) !== '删除'))
ok('左栏仍只有分支树', byClass(t8, 'dsh-git-left').length === 1 && byClass(t8, 'dsh-git-side').length >= 1)
