#!/usr/bin/env node
/* The build: the two files the bridge loads are the ordered concatenation of
   the source fragments under src/. There is no transformation, no bundler and
   no minifier — the fragments share one scope, exactly as the single file did,
   and this script only puts them back in order.

   Edit src/, run `node build.mjs`, then `cordis_stop` + `cordis_run` to make the
   running plugin re-read the result. `node build.mjs --check` reports whether
   host.js and client.js on disk are current, which is what the test runner
   asserts before it trusts a green run. */

import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.dirname(new URL(import.meta.url).pathname)

/* Order is the whole of the structure: a fragment may use anything the
   fragments above it defined, and nothing below. */
export const TARGETS = [
  {
    out: 'host.js',
    parts: [
      'src/host/00-plugin.js',
      'src/host/10-shell.js',
      'src/host/20-safety.js',
      'src/host/30-render.js',
      'src/host/40-tools.js',
      'src/host/50-graph.js',
      'src/host/60-reads.js',
      'src/host/70-config.js',
      'src/host/80-rpc.js',
    ],
  },
  {
    out: 'client.js',
    parts: [
      'src/client/00-plugin.js',
      'src/client/10-state.js',
      'src/client/12-window.js',
      'src/client/20-prefs.js',
      'src/client/30-watch.js',
      'src/client/40-format.js',
      'src/client/42-tree.js',
      'src/client/44-twisty.js',
      'src/client/46-css.js',
      'src/client/50-log.js',
      'src/client/52-detail.js',
      'src/client/54-changes.js',
      'src/client/56-setup.js',
      'src/client/58-branchinfo.js',
      'src/client/60-icons.js',
      'src/client/62-branchstate.js',
      'src/client/70-branchpicker.js',
      'src/client/80-panel.js',
      'src/client/90-settings.js',
      'src/client/92-chip.js',
      'src/client/94-popover.js',
      'src/client/98-register.js',
    ],
  },
]

function banner(target) {
  return '/* GENERATED by build.mjs from ' + target.parts.length + ' fragments under src/ — edit those, not this file. */\n'
}

export function render(target) {
  const bodies = target.parts.map(function (rel) {
    const file = path.join(ROOT, rel)
    if (!fs.existsSync(file)) throw new Error('missing source fragment: ' + rel)
    return fs.readFileSync(file, 'utf8')
  })
  return banner(target) + bodies.join('')
}

export function buildAll(write) {
  const report = []
  for (const target of TARGETS) {
    const next = render(target)
    const file = path.join(ROOT, target.out)
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
    const stale = current !== next
    if (write && stale) fs.writeFileSync(file, next)
    report.push({ out: target.out, stale: stale, bytes: Buffer.byteLength(next) })
  }
  return report
}

const invokedDirectly = process.argv[1] !== undefined && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)
if (invokedDirectly) {
  const check = process.argv.indexOf('--check') >= 0
  const report = buildAll(check !== true)
  let bad = 0
  for (const row of report) {
    const state = row.stale ? (check ? 'STALE' : 'written') : 'current'
    if (check && row.stale) bad += 1
    console.log(row.out.padEnd(12) + state.padEnd(9) + String(row.bytes).padStart(8) + ' bytes')
  }
  if (bad > 0) {
    console.error('build: ' + String(bad) + ' target(s) are not up to date — run `node build.mjs`')
    process.exit(1)
  }
}
