#!/usr/bin/env node
/* Build the publishable package halves from the very same fragments the
   dynamic bridge loads.

   build.mjs renders host.js / client.js as function bodies for the bridge.
   Here each body is wrapped — a real ESM module on the Host side, a
   __ModuleLoader__ classic script on the Client side — with the preludes under
   src/pkg/ supplying the two things only the bridge used to provide: the
   \`harness\` shim and \`host.call\`. Edit src/, then run this, then run
   build.mjs; both artifacts must stay current. */

import fs from 'node:fs'
import path from 'node:path'
import { TARGETS } from './build.mjs'

const ROOT = path.dirname(new URL(import.meta.url).pathname)

function partsOf(out) {
  const target = TARGETS.find(function (row) { return row.out === out })
  if (target === undefined) throw new Error('build.mjs no longer declares ' + out)
  return target.parts
}

/* Order is the whole of the structure, exactly as in build.mjs: the prelude,
   then the shared body fragments, then the postlude that exports the result. */
export const PACKAGE_TARGETS = [
  {
    out: 'lib/index.js',
    pre: 'src/pkg/host-pre.js',
    parts: partsOf('host.js'),
    post: 'src/pkg/host-post.js',
  },
  {
    out: 'client/client.js',
    pre: 'src/pkg/client-pre.js',
    parts: partsOf('client.js'),
    post: 'src/pkg/client-post.js',
  },
]

function read(rel) {
  const file = path.join(ROOT, rel)
  if (!fs.existsSync(file)) throw new Error('missing source fragment: ' + rel)
  return fs.readFileSync(file, 'utf8')
}

export function render(target) {
  const banner = '/* GENERATED by build-package.mjs from ' + String(target.parts.length) + ' fragments under src/ — edit those, not this file. */\n'
  const pieces = [banner, read(target.pre)]
  for (const rel of target.parts) pieces.push(read(rel))
  pieces.push(read(target.post))
  return pieces.join('')
}

export function buildAll(write) {
  const report = []
  for (const target of PACKAGE_TARGETS) {
    const next = render(target)
    const file = path.join(ROOT, target.out)
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
    const stale = current !== next
    if (write && stale) {
      fs.mkdirSync(path.dirname(file), { recursive: true })
      fs.writeFileSync(file, next)
    }
    report.push({ out: target.out, stale: stale, bytes: Buffer.byteLength(next) })
  }
  return report
}

const invokedDirectly = process.argv[1] !== undefined && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)
if (invokedDirectly) {
  const check = process.argv.indexOf('--check') >= 0
  const report = buildAll(check !== true)
  let bad = 0
  for (const row of report) {
    const state = row.stale ? (check ? 'STALE' : 'written') : 'current'
    if (check && row.stale) bad += 1
    console.log(row.out.padEnd(18) + state.padEnd(9) + String(row.bytes).padStart(8) + ' bytes')
  }
  if (bad > 0) {
    console.error('build-package: ' + String(bad) + ' target(s) are not up to date — run \`node build-package.mjs\`')
    process.exit(1)
  }
}
